# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e062a97989e3a79dc4f0dcbe8a8ef0a1f36e443ea19bf8e2aec4c7f6b859c34673f0a6daf22acc2b54822785041346aeb4e305d20886b5b4862f00af25dda8d2

test:
  secret_key_base: 6e995138d046372cadfe53252a64ef40e0deca0454cef1991b2872b9b6e50c16e1b338a9c1800049f4a9b86a6ce6b19692a735aa76f877c1f5ebd67da329a9e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
